name: EOL Blocker

on:
  pull_request:
    branches: [ main ]

jobs:
  check_pull_request_job:
    runs-on: ubuntu-latest
    name: Check files for CRLF
    steps:
    - name: Validate files
      with:
        repoToken: ${{ secrets.EOL_BLOCKER_TOKEN}}
      id: validate
      uses: microsoftgraph/eol-blocker@v1.0.6.alpha.2
