name: Node.js CI

on:
  pull_request:
    branches: release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Verify npm all runs and build output matches
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm ci
    - run: npm run all
    - name: Verify no unstaged changes
      run: test/verify-no-unstaged-changes.sh
